data(iris)
source("./src/em.R")
clusty_iris = clust(iris[,1:4], 1:6 , 20, "kmeans", 0.1)
plot_result(clusty_iris)
plot(iris[,3], iris[,4], col=best_model(clusty_iris,"bic")$Z)
library(mclust)
clusty2_iris <- Mclust(iris[1:4],G = 2:8, modelNames = "VVV")
plot(iris[,3], iris[,4], col=clusty2_iris$classification)
clusty2_bic = mclustBIC(iris[1:4],G = 2:8, modelNames = "VVV")
clusty2_icl = mclustICL(iris[1:4],G = 2:8, modelNames = "VVV")
plot(clusty2_bic)
plot(clusty2_icl)
