data(iris)
source("../src/em.R")
clusty = clust(iris[,1:4], 1:15, 10, "kmeans", 0.01)
plot(iris[,3], iris[,4], col=apply(clusty[[1]][[2]]$Z, 1, which.max))
library(Rmixmod)
#clusty2 = mixmodCluster(data=iris, nbCluster=2:5, dataType="composite")
plot_result(clusty)
